split and patch paramiko

diff --git a/.github/workflows/ssh-step-docker.yml b/.github/workflows/ssh-step-docker.yml
--- a/.github/workflows/ssh-step-docker.yml
+++ b/.github/workflows/ssh-step-docker.yml
@@ -24,14 +24,14 @@ jobs:
     - name: Checkout the repo
       uses: actions/checkout@v4.1.1
 
-    # - name: Set up Python
-    #   uses: actions/setup-python@v5.0.0
-    #   with:
-    #     python-version: "3.10"
+    - name: Set up Python
+      uses: actions/setup-python@v5.0.0
+      with:
+        python-version: "3.10"
 
-    # - name: Install dependencies
-    #   run: |
-    #     pip install paramiko==3.4
+    - name: Install dependencies
+      run: |
+        pip install paramiko==3.4
 
     - name: Install smallstep
       run: |
@@ -39,79 +39,41 @@ jobs:
         sudo dpkg -i step-cli_amd64.deb
         which step
 
-    # - name: Setup client
-    #   run: |
-    #     mkdir -p ~/.ssh
-    #     echo "@cert-authority * ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJJM+jkIdieQvdPb8DwnfnJudEc9PgVBqLDWHKgvqoIiMXhuIyGstQ9ULOBMdJkqxMjkRTFZp1iFvIk+iU6hwTA=" >> ~/.ssh/known_hosts
-
     - name: Build Docker
       run: |
         docker build -t step-ca --no-cache --progress=plain . 2>&1 | tee build.log
-        docker network create --subnet=172.18.0.0/16 mynet123
 
-    - uses: actions/upload-artifact@v4
-      with:
-        path: build.log
+    - name: Setup Network
+      run: |
+        docker network create --subnet=172.18.0.0/16 mynet123
+        sudo echo "172.18.0.22 stepca" | sudo tee -a /etc/hosts
 
     - name: Startup step ca
       run: |
-        docker run --hostname testhost --net mynet123 --ip 172.18.0.22 -p 2222:22 step-ca 1> docker.out 2> docker.err &
-        sleep 10
-        echo password > password.txt
-        sudo echo "172.18.0.22 stepca" | sudo tee -a /etc/hosts
-        FINGERPRINT=$(grep "Root fingerprint" build.log | awk '{print $NF}')
-        echo "${FINGERPRINT:?}"
+        nohup docker run --hostname testhost --net mynet123 --ip 172.18.0.22 -p 2222:22 step-ca 1> docker.out 2> docker.err < /dev/null &
+        sleep 5
+
+    - name: Add /root/.step/certs/ssh_host_ca_key.pub to .ssh/known_hosts
+      run: |
         mkdir -p ~/.ssh
         grep cert-authority build.log | awk '{print $3, $4, $5, $6}' >> ~/.ssh/known_hosts
         cat ~/.ssh/known_hosts
+
+    - name: Bootstrap step ca
+      run: |
+        FINGERPRINT=$(grep "Root fingerprint" build.log | awk '{print $NF}')
+        echo "${FINGERPRINT:?}"
         step ca bootstrap --fingerprint "$FINGERPRINT" --ca-url=https://stepca:8443
+
+    - name: Login
+      run: |
         eval $(ssh-agent)
+        echo password > password.txt
         step ssh login testuser --provisioner step-ca@example.com --password-file password.txt
         ssh-add -l
         ssh testuser@stepca 'echo ciao'
 
-
-    # - name: Test ssh with password
-    #   run: |
-    #     sudo apt-get install sshpass
-    #     sshpass -p 'password' ssh -o StrictHostKeyChecking=no -p 3000 sshuser@localhost 'exit'
-    #     echo $?
-    #     # python test_paramiko.py localhost sshuser 3000 password True
-
-    # - name: Setup key and copy to server
-    #   run: |
-    #     ssh-keygen -t ecdsa -b 256 -f /tmp/sshkey -q -N ""
-    #     sshpass -p 'password' ssh-copy-id -i /tmp/sshkey -p 3000 sshuser@localhost
-        
-    # - name: Setup key and ssh-agent
-    #   run: |
-    #     eval $(ssh-agent)
-    #     ssh-add /tmp/sshkey
-    #     ssh -o StrictHostKeyChecking=no -p 3000 sshuser@localhost 'exit'
-    #     # python test_paramiko.py localhost sshuser 3000 None True
-
-    # - name: Docker kill
-    #   run: |
-    #     docker kill sshserver
-
-    # https://github.com/jonashackt/vagrant-github-actions
-
-    # - name: Upload image
-    #   uses: ishworkh/container-image-artifact-upload@v1.0.0
-    #   with:
-    #     image: "sshserver:latest"
-
-  # compile-win:
-  #   name: Compile site assets
-  #   runs-on: windows-latest
-  #   steps:
-  #   - name: Checkout the repo
-  #     uses: actions/checkout@v2
-  #   - name: Checkout the repo
-  #     uses: actions/checkout@v2
-
-    # - name: sshpass
-    #   run: |
-    #     choco install sshpass
-    #     sshpass -p 'password' ssh -o StrictHostKeyChecking=no -p 3000 sshuser@localhost 'exit'
-    #     echo $?
+        python RCM/tests/test_paramiko.py stepca testuser 22 None True || echo "failed as expected"
+        PARAMIKO_FILE="$(python -c "import paramiko, os; print(os.path.dirname(paramiko.__file__))")/auth_handler.py"
+        sed -i'.bak' -e 's/if key.public_blob:/if hasattr(key, "public_blob") and key.public_blob:/' $PARAMIKO_FILE
+        python RCM/tests/test_paramiko.py stepca testuser 22 None True && echo "success as expected"
